Error executing job with overrides: []
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\model.py", line 37, in evaluate
    wandb.log({
    ~~~~~~~~~^^
        f"{self.name} Training Accuracy": train_acc,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        f"{self.name} CV Score Std Dev": cv_scores.std(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    })
    ^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.errors.Error: You must call wandb.init() before wandb.log()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\train.py", line 30, in <lambda>
    joblib.delayed(lambda model: model.evaluate(X_train, X_test, y_train, y_test))(model)
                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\model.py", line 66, in evaluate
    wandb.log({f"{self.name} Evaluation Error": str(e)})
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.errors.Error: You must call wandb.init() before wandb.log()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Erick\Desktop\Project\Jupyter\DlhJupyterNotebook\train.py", line 29, in main
    joblib.Parallel(n_jobs=-1)(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        joblib.delayed(lambda model: model.evaluate(X_train, X_test, y_train, y_test))(model)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        for model in models.values()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 745, in get_result
    return self._return_or_raise()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Erick\miniconda3\Lib\site-packages\joblib\parallel.py", line 763, in _return_or_raise
    raise self._result
wandb.errors.errors.Error: You must call wandb.init() before wandb.log()

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
